In [1]:
import pandas as pd

In [2]:
file1 = "static/data/sales_by_model.csv"
file1_df = pd.read_csv(file1)

In [9]:
file1_df

,Vehicle,Type,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total
0,Chevy Volt,PHEV,"7,671","23,461","23,094","18,805","15,393","24,739","20,349","18,306","4,915","156,733"
1,Nissan Leaf,EV,"9,674","9,819","22,610","30,200","17,269","14,006","11,230","14,715","12,365","141,888"
2,Smart ED,EV,342,139,923,"2,594","1,387",657,544,"1,219",680,"8,485"
3,Mitsubishi I EV,EV,76,588,"1,029",196,115,94,6,0,0,"2,104"
4,BMW Active E,EV,0,673,0,0,0,0,0,0,0,673
5,Prius PHEV,PHEV,0,"12,749","12,088","13,264","4,191","2,474","20,936","27,595","23,630","116,927"
6,Ford Focus EV,EV,0,683,"1,738","1,964","1,582",901,"1,817",560,0,"9,245"
7,Honda Fit EV,EV,0,93,569,407,2,0,0,0,0,"1,071"
8,Tesla Model S,EV,0,"2,400","19,400","16,750","26,200","30,200","26,500","25,745","15,090","162,285"
9,Toyota RAV4 EV,EV,0,192,"1,005","1,184",18,0,0,0,0,"2,399"
10,Ford C-Max Energi,PHEV,0,"2,374","7,154","8,433","7,591","7,957","8,140",582,0,"42,231"
11,Honda Accord,PHEV,0,0,526,449,64,0,0,0,0,"1,039"
12,Ford Fusion Energi,PHEV,0,0,"6,089","11,550","9,750","15,938","9,632","8,074","7,476","68,509"
13,Chevy Spark,EV,0,0,560,"1,145","2,629","3,035",23,7,0,"7,399"
14,Fiat 500E,EV,0,0,260,"1,503","3,477","3,737","3,336","2,250",632,"15,195"
15,Porsche Panamera S E-Hybrid,PHEV,0,0,51,879,407,393,18,"2,036","1,958","5,742"
16,Cadillac ELR,PHEV,0,0,6,"1,310","1,024",534,17,1,0,"2,892"
17,BMW i3,EV,0,0,0,"6,092","11,024","7,625","6,276","6,117","4,854","41,988"
18,Mercedes B-Class (B250e),EV,0,0,0,774,"1,906",632,744,135,9,"4,200"
19,BMW i8,PHEV,0,0,0,555,"2,265","1,594",488,772,"1,102","6,776"
20,VW e-Golf,EV,0,0,0,357,"4,232","3,937","3,534","1,354","4,863","18,277"
21,Kia Soul EV,EV,0,0,0,359,"1,015","1,728","2,157","1,134",114,"6,507"
22,Porsche Cayenne S E-Hybrid,PHEV,0,0,0,112,"1,163","2,111","1,574","1,022","1,140","7,122"
23,Mercedes S550 Plug,PHEV,0,0,0,0,118,550,666,96,371,"1,801"
24,Volvo-XC90 Plug In,PHEV,0,0,0,0,86,"2,015","2,358","1,387","1,710","7,556"
25,Tesla Model X,EV,0,0,0,0,208,"19,600","21,700","26,100","19,425","87,033"
26,BMW X5,PHEV,0,0,0,0,892,"5,995","5,349","4,434",167,"16,837"
27,Hyundai Sonata Plug In,PHEV,0,0,0,0,15,"3,000","2,254",460,456,"6,185"
28,Audi A3 Plug In,PHEV,0,0,0,0,0,"4,280","2,877","2,597",437,"10,191"
29,BMW 3-series Plug-In,PHEV,0,0,0,0,0,880,"4,141","2,600",705,"8,326"
30,Mercedes GLE 550e,PHEV,0,0,0,0,0,231,463,966,"1,509","3,169"
31,BMW 7-series Plug-in,PHEV,0,0,0,0,0,23,707,339,80,"1,149"
32,Mercedes C350We,PHEV,0,0,0,0,0,171,817,"1,721","2,172","4,881"
33,Chevy Bolt,EV,0,0,0,0,0,579,"23,297","18,019","16,313","58,208"
34,Kia Optima Plug-in,PHEV,0,0,0,0,0,0,"1,512",965,350,"2,827"
35,Hyundai Ioniq EV,EV,0,0,0,0,0,0,432,345,739,"1,516"
36,Chrysler Pacifica Plug-in Hybrid,PHEV,0,0,0,0,0,0,"2,981","7,062","5,811","15,854"
37,Cadillac CT6,PHEV,0,0,0,0,0,0,205,231,25,461
38,BMW 5-Series Plug in,PHEV,0,0,0,0,0,0,"3,759","8,664","5,442","17,865"
39,MINI Countryman S E,PHEV,0,0,0,0,0,0,475,"1,564",494,"2,533"
40,Porsche Panamera 4 E-H,PHEV,0,0,0,0,0,0,0,0,0,0
41,Tesla Model 3,EV,0,0,0,0,0,0,"1,770","139,782","154,840","296,392"
42,Honda Clarity BEV,EV,0,0,0,0,0,0,"1,126",948,742,"2,816"
43,Volvo XC60 Plug In,PHEV,0,0,0,0,0,0,356,"2,267","1,682","4,305"
44,Volvo S90 Plug In,PHEV,0,0,0,0,0,0,112,437,407,956
45,Honda Clarity Plug-in,PHEV,0,0,0,0,0,0,903,"18,602","10,728","30,233"
46,Mitsubishi Outlander Plug In,PHEV,0,0,0,0,0,0,0,"4,166","2,810","6,976"
47,Hyundai Ioniq Plug-In,PHEV,0,0,0,0,0,0,0,"1,590","1,765","3,355"
48,Kia Niro Plug In,PHEV,0,0,0,0,0,0,0,"3,389","4,051","7,440"
49,Mercedes GLC 350e Hybrid,PHEV,0,0,0,0,0,0,0,567,"2,459","3,026"
50,Jaguar I-Pace,EV,0,0,0,0,0,0,0,393,"2,594","2,987"
51,Hyundai Kona Electric,EV,0,0,0,0,0,0,0,0,"1,721","1,721"
52,Subaru Crosstrek Hybrid,PHEV,0,0,0,0,0,0,0,0,880,880
53,Audi e-tron,EV,0,0,0,0,0,0,0,0,"5,369","5,369"
54,Kia Niro EV,EV,0,0,0,0,0,0,0,0,"1,562","1,562"
55,Total,NaN,"17,763","53,171","97,102","118,882","114,023","159,616","195,581","361,315","326,644","1,444,097"

In [8]:
file1_df["2011"] =  file1_df.Total.astype(float)

ValueError: could not convert string to float: '156,733'